runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxPriceUnder100Shop
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxCapacity8GB
  script: unused
  login: optional
  secure: optional
- url: /addSupplier
  script: unused
  login: optional
  secure: optional
- url: /loadKingston
  script: unused
  login: optional
  secure: optional
- url: /deleteCart
  script: unused
  login: optional
  secure: optional
- url: /deleteSupplier
  script: unused
  login: optional
  secure: optional
- url: /loadProduct
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxCapacity32GB
  script: unused
  login: optional
  secure: optional
- url: /forgotPassword
  script: unused
  login: optional
  secure: optional
- url: /xuatExcelControl
  script: unused
  login: optional
  secure: optional
- url: /categoryShop
  script: unused
  login: optional
  secure: optional
- url: /sellCart
  script: unused
  login: optional
  secure: optional
- url: /addAccount
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxCapacity4GB
  script: unused
  login: optional
  secure: optional
- url: /addAmountCart
  script: unused
  login: optional
  secure: optional
- url: /manager
  script: unused
  login: optional
  secure: optional
- url: /top5nhanvien
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxPrice100To200Shop
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxShop
  script: unused
  login: optional
  secure: optional
- url: /totalMoneyCart
  script: unused
  login: optional
  secure: optional
- url: /doanhThuTheoThu
  script: unused
  login: optional
  secure: optional
- url: /searchAjax
  script: unused
  login: optional
  secure: optional
- url: /delete
  script: unused
  login: optional
  secure: optional
- url: /shop
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxCapacity2GB
  script: unused
  login: optional
  secure: optional
- url: /detail
  script: unused
  login: optional
  secure: optional
- url: /search
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxCapacity16GB
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxPriceAbove200Shop
  script: unused
  login: optional
  secure: optional
- url: /home
  script: unused
  login: optional
  secure: optional
- url: /managerAccount
  script: unused
  login: optional
  secure: optional
- url: /top5khachhang
  script: unused
  login: optional
  secure: optional
- url: /edit
  script: unused
  login: optional
  secure: optional
- url: /loadAllAmountCart
  script: unused
  login: optional
  secure: optional
- url: /deleteAccount
  script: unused
  login: optional
  secure: optional
- url: /signup
  script: unused
  login: optional
  secure: optional
- url: /doanhThuTheoThang
  script: unused
  login: optional
  secure: optional
- url: /managerCart
  script: unused
  login: optional
  secure: optional
- url: /editProfile
  script: unused
  login: optional
  secure: optional
- url: /login
  script: unused
  login: optional
  secure: optional
- url: /order
  script: unused
  login: optional
  secure: optional
- url: /admin
  script: unused
  login: optional
  secure: optional
- url: /category
  script: unused
  login: optional
  secure: optional
- url: /top10
  script: unused
  login: optional
  secure: optional
- url: /load
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxHoaDon
  script: unused
  login: optional
  secure: optional
- url: /managerSupplier
  script: unused
  login: optional
  secure: optional
- url: /searchAjaxPriceMinToMax
  script: unused
  login: optional
  secure: optional
- url: /loadKingmax
  script: unused
  login: optional
  secure: optional
- url: /subAmountCart
  script: unused
  login: optional
  secure: optional
- url: /addReview
  script: unused
  login: optional
  secure: optional
- url: /logout
  script: unused
  login: optional
  secure: optional
- url: /add
  script: unused
  login: optional
  secure: optional
- url: /addCart
  script: unused
  login: optional
  secure: optional
- url: /hoaDon
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
